<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>CoreMVC.Web-UserSecrets</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.7" />
    <PackageReference Include="Microsoft.Build" Version="17.13.9" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="18.6.3" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.7" />
    <PackageReference Include="Microsoft.Identity.Web" Version="2.11.0" />
    <PackageReference Include="NuGet.Packaging" Version="7.6.0" />
    <PackageReference Include="NuGet.Protocol" Version="7.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoreMVC.Application\CoreMVC.Application.csproj" />
    <ProjectReference Include="..\CoreMVC.Infrastructure\CoreMVC.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="CoreMVC\**" />
    <Content Remove="CoreMVC\**" />
    <EmbeddedResource Remove="CoreMVC\**" />
    <None Remove="CoreMVC\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Identity\Data\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
