// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace NZWalks.API.Models;

public partial class MVCNetNZWalksContext : DbContext
{
    public MVCNetNZWalksContext(DbContextOptions<MVCNetNZWalksContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Difficulty> Difficulties { get; set; }

    public virtual DbSet<Region> Regions { get; set; }

    public virtual DbSet<Walk> Walks { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Difficulty>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Difficul__3214EC07D04C3AD2");

            entity.ToTable("Difficulty");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Name).IsRequired();
        });

        modelBuilder.Entity<Region>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Regions__3214EC072CFFE55B");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Code).IsRequired();
            entity.Property(e => e.Name).IsRequired();
        });

        modelBuilder.Entity<Walk>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Walks__3214EC072F6245D5");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Description).IsRequired();
            entity.Property(e => e.Name).IsRequired();

            entity.HasOne(d => d.Difficulty).WithMany(p => p.Walks)
                .HasForeignKey(d => d.DifficultyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Walks_Difficulty");

            entity.HasOne(d => d.Region).WithMany(p => p.Walks)
                .HasForeignKey(d => d.RegionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Walks_Regions");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}