// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NZWalks.API.Models;

public partial class Region
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string RegionImageUrl { get; set; }

    public virtual ICollection<Walk> Walks { get; set; } = new List<Walk>();
}