// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NZWalks.API.Models;

public partial class Walk
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public double LengthInKm { get; set; }

    public string WalkImageUrl { get; set; }

    public int RegionId { get; set; }

    public int DifficultyId { get; set; }

    public virtual Difficulty Difficulty { get; set; }

    public virtual Region Region { get; set; }
}