using Microsoft.EntityFrameworkCore;
using NZWalks.API.Models;

namespace NZWalks.API.Repositories
{
    public class DifficultyRepository : IDifficultyRepository
    {
        private readonly MVCNetNZWalksContext nZWalksDbContext;

        public DifficultyRepository(MVCNetNZWalksContext nZWalksDbContext)
        {
            this.nZWalksDbContext = nZWalksDbContext;
        }

        public async Task<Difficulty> AddAsync(Difficulty difficulty)
        {
            // Id is generated by the database (identity column)
            await nZWalksDbContext.Difficulties.AddAsync(difficulty);
            await nZWalksDbContext.SaveChangesAsync();
            return difficulty;
        }

        public async Task<Difficulty?> DeleteAsync(int id)
        {
            var existingDifficulty = await nZWalksDbContext.Difficulties.FindAsync(id);

            if (existingDifficulty == null)
            {
                return null;
            }

            nZWalksDbContext.Difficulties.Remove(existingDifficulty);
            await nZWalksDbContext.SaveChangesAsync();
            return existingDifficulty;
        }

        public async Task<bool> HasWalksAsync(int id)
        {
            return await nZWalksDbContext.Walks.AnyAsync(x => x.DifficultyId == id);
        }

        public async Task<IEnumerable<Difficulty>> GetAllAsync()
        {
            return await nZWalksDbContext.Difficulties.ToListAsync();
        }

        public async Task<Difficulty?> GetAsync(int id)
        {
            return await nZWalksDbContext.Difficulties.FirstOrDefaultAsync(x => x.Id == id);
        }

        public async Task<Difficulty?> UpdateAsync(int id, Difficulty difficulty)
        {
            var existingDifficulty = await nZWalksDbContext.Difficulties.FindAsync(id);

            if (existingDifficulty != null)
            {
                existingDifficulty.Name = difficulty.Name;
                await nZWalksDbContext.SaveChangesAsync();
                return existingDifficulty;
            }

            return null;
        }
    }
}
