using Microsoft.EntityFrameworkCore;
using NZWalks.API.Models;

namespace NZWalks.API.Repositories
{
    public class RegionRepository : IRegionRepository
    {
        private readonly MVCNetNZWalksContext nZWalksDbContext;

        public RegionRepository(MVCNetNZWalksContext nZWalksDbContext)
        {
            this.nZWalksDbContext = nZWalksDbContext;
        }

        public async Task<Region> AddAsync(Region region)
        {
            // Id is generated by the database (identity column)
            await nZWalksDbContext.Regions.AddAsync(region);
            await nZWalksDbContext.SaveChangesAsync();
            return region;
        }

        public async Task<Region?> DeleteAsync(int id)
        {
            var existingRegion = await nZWalksDbContext.Regions.FindAsync(id);

            if (existingRegion == null)
            {
                return null;
            }

            nZWalksDbContext.Regions.Remove(existingRegion);
            await nZWalksDbContext.SaveChangesAsync();
            return existingRegion;
        }

        public async Task<bool> HasWalksAsync(int id)
        {
            return await nZWalksDbContext.Walks.AnyAsync(x => x.RegionId == id);
        }

        public async Task<IEnumerable<Region>> GetAllAsync()
        {
            return await nZWalksDbContext.Regions.ToListAsync();
        }

        public async Task<Region?> GetAsync(int id)
        {
            return await nZWalksDbContext.Regions.FirstOrDefaultAsync(x => x.Id == id);
        }

        public async Task<Region?> UpdateAsync(int id, Region region)
        {
            var existingRegion = await nZWalksDbContext.Regions.FindAsync(id);

            if (existingRegion != null)
            {
                existingRegion.Code = region.Code;
                existingRegion.Name = region.Name;
                existingRegion.RegionImageUrl = region.RegionImageUrl;
                await nZWalksDbContext.SaveChangesAsync();
                return existingRegion;
            }

            return null;
        }
    }
}
